#!/bin/bash
echo "📝 RLS 정책 적용 시작..."
echo ""
echo "적용할 정책:"
echo "- members: 로그인/회원가입 허용"
echo "- customer_orders: 주문조회 허용"
echo "- coupons: 쿠폰 조회/사용 허용"
echo "- sessions: 세션 관리 허용"
echo ""
echo "⚠️  Supabase SQL Editor에서 실행:"
echo "1. create_rls_policies_safe.sql 실행"
echo "2. 확인 쿼리로 정책 적용 확인"
echo ""
echo "테스트 필요:"
echo "- Homepage 로그인"
echo "- 회원가입"
echo "- 주문조회"
